In [2]:
import pandas as pd

In [3]:
s = pd.Series([10,20,30])
print(s)

0    10
1    20
2    30
dtype: int64

In [4]:
_list = [40,50,60]
s1 = pd.Series(_list,index = ['a','b','c'])
print(s1)

a    40
b    50
c    60
dtype: int64

In [6]:
_list_ex = [['Alice',25],['Bob',30]]
df = pd.DataFrame(_list_ex, columns=['Name','Age'])
df

    Name  Age
0  Alice   25
1    Bob   30

In [14]:
data = {
    'Name' : ['Alice' , 'Bob', 'Charlie'],
    'Age' : [25, 30, 45],
    'Marks' : [43, 95, 60]
}

df = pd.DataFrame(data, index = [1,2,3])
df

      Name  Age  Marks
1    Alice   25     43
2      Bob   30     95
3  Charlie   45     60

In [20]:
data = {
    'Name' : ['Alice' , 'Bob', 'Charlie'],
    'Age' : [25, 30, 45],
    'Marks' : [43, 95, 60]
}

df = pd.DataFrame(data, index=[[(i + 1) for i in range(3)]])

df

      Name  Age  Marks
1    Alice   25     43
2      Bob   30     95
3  Charlie   45     60